using System.Runtime.InteropServices;
using Microsoft.Extensions.Localization;

// file need to specify ResourceLocation to be able to use localization
// since assembly name != rootNamespace
// assemblyInfo.cs normally autogenerated by inspecting .csproj
// currently (.net 6) there is no option to specify resourceLocation in .csproj

[assembly: ComVisible(false)]

[assembly: Guid("b6c8ddc9-6025-4c2f-af6d-8bbc6c54cd0f")]

[assembly: ResourceLocation("Resources")]
[assembly: RootNamespace("hello_asp_localization")]